package it.geek.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T13:10:52.933+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.geek.it/", name = "HelloInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.geek.it/", className = "it.geek.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.geek.it/", className = "it.geek.ws.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "nome", targetNamespace = "")
        java.lang.String nome
    );
}
