
package it.geek.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T13:10:52.852+02:00
 * Generated source version: 2.7.5
 * 
 */
public final class HelloInterface_HelloPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.geek.it/", "Hello");

    private HelloInterface_HelloPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Hello.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Hello ss = new Hello(wsdlURL, SERVICE_NAME);
        HelloInterface port = ss.getHelloPort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_nome = "_sayHello_nome928748064";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_nome);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }
    
    public static String call(String param) throws java.lang.Exception {
        URL wsdlURL = Hello.WSDL_LOCATION;
      
        Hello ss = new Hello(wsdlURL, SERVICE_NAME);
        HelloInterface port = ss.getHelloPort();  
        
        System.out.println("Invoking sayHello...");
        return port.sayHello(param);

    }

}
